# Generated by Django 3.0.2 on 2020-02-12 23:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(max_length=40, unique=True)),
                ('img_bandeira', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem do cartao')),
            ],
        ),
    ]
