# Generated by Django 2.1.5 on 2019-11-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50, unique=True)),
                ('numero_banco', models.CharField(max_length=10, unique=True)),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Ativo')),
            ],
            options={
                'ordering': ('banco',),
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=15)),
                ('tipo_conta', models.CharField(choices=[('Corrente', 'Corrente'), ('Poupança', 'Poupança')], default='Corrente', max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Ativo')),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.Banco', verbose_name='Banco')),
            ],
        ),
    ]
