# Generated by Django 3.0.2 on 2020-02-10 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_auto_20200210_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0002_auto_20200120_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subordinado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=32)),
                ('tipo_documento', models.CharField(default='CPF', max_length=20)),
                ('mcc', models.CharField(default='8999', max_length=6, null=True)),
                ('nome_contato', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('codigo_banco', models.CharField(default='', max_length=20)),
                ('tipo_conta', models.CharField(choices=[('Conta corrente', 'CheckingAccount'), ('Conta poupança', 'SavingsAccount')], default='CheckingAccount', max_length=40)),
                ('numero_conta', models.CharField(default='', max_length=30)),
                ('dig_verif', models.CharField(default='', max_length=5)),
                ('agencia', models.CharField(default='', max_length=10)),
                ('digito_agencia', models.CharField(default='', max_length=5)),
                ('documento_conta', models.CharField(default='', max_length=200)),
                ('tipo_doc_conta', models.CharField(default='', max_length=30)),
                ('librar_para_braspg', models.BooleanField(default=False)),
                ('id_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.Banco')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
